### ISSUE TITLE
Use Instance#getWorldAge instead of System#currentTimeMillis

### ISSUE THREAD

**Issue by Marlonzockt** [Minestom/Arena#48]
Shouldn't https://github.com/Minestom/Arena/blob/aee77686437fdaf24310d60a996de8a08e0b7370/src/main/java/net/minestom/arena/feature/BowFeature.java#L30-L36
use the instance world age rather than current time millis?

**Comment by Marlonzockt** [comment]
if you were to change tps, idk. I mean I feel like it's a better convention, especially as this is meant to be a project where you can be like "look at how it's implemented here"

**Comment by kiip1** [comment]
Current time millis is the right way to do this; you don't want the charge time to rely on instances. What if you change instances during bow charging? It would only cause unexpected behaviour.

**Comment by Marlonzockt** [comment]
The point would be having the charge time rely on ticks rather than seconds, but I can see your choice
